subgraphs:
  API_SERVICE_AUTH:
    routing_url: 'http://localhost:4002/graphql'
    schema:
      file: ./graphql/API_SERVICE_AUTH.graphql
  API_SERVICE_LOCAL:
    routing_url: 'http://localhost:4001/'
    schema:
      file: ./graphql/API_SERVICE_LOCAL.graphql
