subgraphs:
  API_SERVICE_AUTH:
    routing_url: 'http://ec2-3-140-244-169.us-east-2.compute.amazonaws.com/'
    schema:
      file: ./graphql/API_SERVICE_AUTH.graphql
  API_SERVICE_LICENSE:
    routing_url: 'http://ec2-18-116-30-81.us-east-2.compute.amazonaws.com/'
    schema:
      file: ./graphql/API_SERVICE_LICENSE.graphql
  API_SERVICE_LOCAL:
    routing_url: 'http://localhost:4001/'
    schema:
      file: ./graphql/API_SERVICE_LOCAL.graphql
  API_SERVICE_RABBITMQ_CONSUME:
    routing_url: 'http://ec2-18-219-122-41.us-east-2.compute.amazonaws.com/'
    schema:
      file: ./graphql/API_SERVICE_RABBITMQ_CONSUME.graphql
