subgraphs:
  apiLocal:
    routing_url: http://localhost:4001/
    schema:
      file: ./api.graphql
  auth:
    routing_url: http://ip-172-31-18-186.us-east-2.compute.internal:4002/
    schema:
      file: ./auth.graphql
